---

services:

  jobmanager:
    image: flink
    hostname: jobmanager
    container_name: jobmanager
    command: ["jobmanager"]
    ports:
      - 8081:8081 # Flink WebUI
    networks:
      - net-flink
    env_file:
      - .env.flink
    volumes:
      - ./datasets:/datasets

  taskmanager01:
    image: flink
    hostname: taskmanager01
    container_name: taskmanager01
    command:  ["taskmanager"]
    networks:
      - net-flink
    env_file:
      - .env.flink
    depends_on:
      - jobmanager
    volumes:
      - ./datasets:/datasets

  taskmanager02:
    image: flink
    hostname: taskmanager02
    container_name: taskmanager02
    command:  ["taskmanager"]
    networks:
      - net-flink
    env_file:
      - .env.flink
    depends_on:
      - jobmanager
    volumes:
      - ./datasets:/datasets

networks:
  net-flink:
    driver: bridge


